service:
  name: personalkanban-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'development'}
  region: ${opt:region, 'us-west-1'}

  environment:
    MYKANBAN_TABLE: mykanban-${self:provider.stage}
    GSI_INDEX_NAME: UserIdWithCreatedAtIndexes
    GSI_STATE_INDEX_NAME: StateIndexes
    MYKANBANUSERS_TABLE: mykanbanusers-${self:provider.stage}
    GSI_USERSACTIVE_INDEX_NAME: ActiveIndexes


functions:
# GET User Tasks
  GetTasks:
    handler: src/lambda/http/getTasks.handler
    events:
      - http:
          method: get
          path: tasks
          cors: true
    iamRoleStatementsName: ${self:service.name}-get-tasks-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}/index/UserIdIndex

# GET Public Tasks
  GetPublicTasks:
    handler: src/lambda/http/getPublictasks.handler
    events:
      - http:
          method: get
          path: public/tasks
          cors: true
    iamRoleStatementsName: ${self:service.name}-get-public-tasks-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}/index/StateIndexes
  
  CreateTasks:
    handler: src/lambda/http/createTask.handler
    events:
      - http:
          method: post
          path: tasks
          cors: true
          request:
            schema:
              application/json: ${file(src/validators/create-task.json)}
    iamRoleStatementsName: ${self:service.name}-create-task-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBANUSERS_TABLE}

  UpdateTask:
    handler: src/lambda/http/updateTask.handler
    events:
      - http:
          method: patch
          path: tasks/{taskId}
          cors: true
    iamRoleStatementsName: ${self:service.name}-update-task-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}

  DeleteTask:
    handler: src/lambda/http/deleteTask.handler
    events:
      - http:
          method: delete
          path: tasks/{taskId}
          cors: true
    iamRoleStatementsName: ${self:service.name}-delete-task-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBAN_TABLE}

# USER FUNCTIONS

# GET Users
  GetUsers:
    handler: src/lambda/http/getUsers.handler
    events:
      - http:
          method: get
          path: users
          cors: true
    iamRoleStatementsName: ${self:service.name}-get-users-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBANUSERS_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBANUSERS_TABLE}/index/ActiveIndexes
  # Create User
  CreateUser:
    handler: src/lambda/http/createUser.handler
    events:
      - http:
          method: post
          path: users
          cors: true
          request:
            schema:
              application/json: ${file(src/validators/create-user.json)}
    iamRoleStatementsName: ${self:service.name}-create-user-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBANUSERS_TABLE}
   # Update User
  UpdateUser:
    handler: src/lambda/http/updateUser.handler
    events:
      - http:
          method: patch
          path: users/{userId}
          cors: true
    iamRoleStatementsName: ${self:service.name}-update-user-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBANUSERS_TABLE}
   # Delete User
  DeleteUser:
    handler: src/lambda/http/deleteUser.handler
    events:
      - http:
          method: delete
          path: users/{userId}
          cors: true
    iamRoleStatementsName: ${self:service.name}-delete-user-role-${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.MYKANBANUSERS_TABLE}

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: taskId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: state
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: taskId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI_INDEX_NAME}
            KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ${self:provider.environment.GSI_STATE_INDEX_NAME}
            KeySchema:
            - AttributeName: state
              KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.MYKANBAN_TABLE}
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: active
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.GSI_USERSACTIVE_INDEX_NAME}
            KeySchema:
            - AttributeName: active
              KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.MYKANBANUSERS_TABLE}